### ISSUE TITLE
Tests for opentracing-flowid-servlet fail when run on OpenJDK 11

### ISSUE THREAD

**Issue by ePaul** [zalando/opentracing-toolbox#524]
## Description

When building the project under Java 11, some tests of the module opentracing-flowid-servlet fail with a `java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException` or `java.lang.NoClassDefFoundError: Could not initialize class com.jayway.restassured.RestAssured`.

## Expected Behavior

Tests should succeed.

## Actual Behavior

Tests are failing.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.zalando.opentracing.flowid.servlet.FlowFilterTest
[ERROR] Tests run: 5, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.122 s <<< FAILURE! - in org.zalando.opentracing.flowid.servlet.FlowFilterTest
[ERROR] shouldPropagateFlowAsFlowIdHeader  Time elapsed: 0.841 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.zalando.opentracing.flowid.servlet.FlowFilterTest.shouldPropagateFlowAsFlowIdHeader(FlowFilterTest.java:61)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.zalando.opentracing.flowid.servlet.FlowFilterTest.shouldPropagateFlowAsFlowIdHeader(FlowFilterTest.java:61)

[ERROR] shouldUseFlowIdFromBaggage  Time elapsed: 0.013 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.jayway.restassured.RestAssured
	at org.zalando.opentracing.flowid.servlet.FlowFilterTest.shouldUseFlowIdFromBaggage(FlowFilterTest.java:48)

[ERROR] shouldUseTraceIdAsFlowId  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.jayway.restassured.RestAssured
	at org.zalando.opentracing.flowid.servlet.FlowFilterTest.shouldUseTraceIdAsFlowId(FlowFilterTest.java:36)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   FlowFilterTest.shouldPropagateFlowAsFlowIdHeader:61 » NoClassDefFound javax/xm...
[ERROR]   FlowFilterTest.shouldUseFlowIdFromBaggage:48 NoClassDefFound Could not initial...
[ERROR]   FlowFilterTest.shouldUseTraceIdAsFlowId:36 NoClassDefFound Could not initializ...
[INFO] 
[ERROR] Tests run: 5, Failures: 0, Errors: 3, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for opentracing-toolbox 3.0.0-SNAPSHOT:
[INFO] 
[INFO] opentracing-toolbox ................................ SUCCESS [  6.594 s]
[INFO] opentracing-flowid-parent .......................... SUCCESS [  1.821 s]
[INFO] opentracing-flowid-servlet ......................... FAILURE [  6.383 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.342 s
[INFO] Finished at: 2021-02-25T21:28:00+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project opentracing-flowid-servlet: There are test failures.
```

## Possible Reason

It seems like Spring-Security (and/or some other library used in those tests) has an implicit dependency on Jaxb, and this is not included in the standard Java library anymore without a separate maven dependency.

## Steps to Reproduce

1. check out the project
2. switch your Java to OpenJDK 11
3. `./mvnw clean install -pl .,opentracing-flowid,opentracing-flowid/opentracing-flowid-servlet`
4. observe the errors.

The same command works with OpenJDK 8. I didn't try other versions.

Other tests might be broken with OpenJDK 11 too, those were the first ones in the list.

## Context

I was trying to build the whole project to see whether my change in #523 was breaking something.

## Your Environment

* Version used: current main branch.

**Comment by whiskeysierra** [comment]
Java 11 doesn't ship JAXB anymore by default. You need to add it as a dependency then. This is not an issue until we start building with Java 11. Anyone who wants to use OpenTracing Toolbox with Java 11 needs to add optional dependencies to their application.
